#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch

exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = /usr/lib/pam_kwallet_init
exec-once = qs -c noctalia-shell
exec-once = pkill -9 wl-paste; wl-paste --watch cliphist store &
exec-once = qs -c overview
