#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
# This really depends on your preferences, e.g. you play games, different keyboards you own, avialable space on the table/touchpad
input {
    kb_layout = it, us
    kb_options = compose:caps, grp:win_space_toggle
    follow_mouse = 1
    
    scroll_method = on_button_down
    scroll_button_lock = true
    scroll_button = 274 # Mouse wheel clicks enable scrolling

    sensitivity = 0.8 # -1.0 - 1.0, 0 means no modification.
    accel_profile = adaptive

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }
}

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
#device {
#    name = epic-mouse-v1
#    sensitivity = -0.5
#}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

