#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
# This really depends on your preferences, e.g. you play games, different keyboards you own, avialable space on the table/touchpad

# DEFAULT SETTINGS (Applies to any device not specifically listed below)
input {
    kb_layout = it, us
    kb_options = compose:caps, grp:win_space_toggle
    follow_mouse = 1
    
    sensitivity = 0.2
    accel_profile = adaptive

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }
}

# Per-device settings
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

# GAMING MOUSE
device {
    # REPLACE with the exact name from `hyprctl devices`
    name = your-gaming-mouse-name
    
    sensitivity = 0
    accel_profile = flat # Flat disables acceleration
    
    # Scroll lock on middle button
    scroll_method = on_button_down
    scroll_button_lock = true
    scroll_button = 274 
}

# TOUCHPAD
device {
    name = elan050a:01-04f3:3158-touchpad
    
    sensitivity = 0.8
    accel_profile = adaptive # Adaptive enables acceleration
}


################
### GESTURES ###
################

# See https://wiki.hypr.land/Configuring/Gestures

# 3 fingers horizontal: Switch workspaces
gesture = 3, horizontal, workspace

# 3 fingers up/down: Toggle Fullscreen
gesture = 3, vertical, fullscreen

# 3 fingers pinch: Toggle floating
gesture = 3, pinch, float

# 3 fingers ping + SUPER: Resize window
gesture = 3, pinch, mod:SUPER, resize
