#####################
### LOOK AND FEEL ###
#####################

# Refer to https://wiki.hypr.land/Configuring/Variables/

# NOTE: Do not put perfromance-related settings here, they belong in performance.conf

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 20
    border_size = 2

    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $primary $tertiary 90deg
    col.inactive_border = $surface $surface_lowest 90deg

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    layout = scrolling # You can also switch to dwindle
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout
dwindle {
    preserve_split = true # You probably want this
}

# https://wiki.hypr.land/Configuring/Scrolling-Layout
scrolling {
  # None to do, I like the default :)
}

# https://wiki.hypr.land/Configuring/Master-Layout
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#cursor
cursor {
    enable_hyprcursor = true
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 10
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

    # https://wiki.hypr.land/Configuring/Variables/#shadow
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 2
        vibrancy = 0.1696
    }
}

# https://wiki.hypr.land/Configuring/Animations/
animations {
    enabled = yes, please :)

    # A cleaner version of MD3 without the bounce
    bezier = standard, 0.2, 0, 0, 1
    # High velocity start, instant lock-in
    bezier = snappy, 0.3, 1, 0, 1 
    # Starts slow, then vanishes instantly
    bezier = fastOut, 0.3, 0, 1, 1 
    # A cleaner version of MD3 without the bounce
    bezier = fluid, 0.05, 0.7, 0.1, 1 

    # Windows 
    animation = windowsIn, 1, 3, snappy, popin 80%
    animation = windowsOut, 1, 3, fastOut, popin 80%
    animation = windowsMove, 1, 3, snappy 

    # Layers
    animation = layersIn, 1, 3, fluid, slide
    animation = layersOut, 1, 3, fastOut, slide
    animation = fadeLayers, 1, 4, standard

    # Workspaces
    animation = workspaces, 1, 4, snappy, slidevert
    animation = specialWorkspaceIn, 1, 4, snappy, slidefade left 40%
    animation = specialWorkspaceOut, 1, 4, snappy, slidefade right 40%

    # Aesthetics
    animation = fade, 1, 3, standard
    animation = border, 1, 5, standard
}

