################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/

# TODO: move to LUA to introduce logic for:
# - when AsusTek is connected, use it as primary and turn off the laptop screen
# - when laptop is not available (i.e., we are using destkop), then make it own and start from 0
# - solve messy use of multiple workspaces on different monitors etc.

# Monitors
$laptop = eDP-1

# Primary Monitor
# Syntax: monitor = name, res@hz, position, scale
monitor = $laptop, 1920x1080@144, 0x0, 1

# NOTE: you should specify here monitors where you want to turn VRR always on (most probably gaming ones)

# Some monnitor I saw in my life
monitor = desc:OOO YZ2748, 1920x1080@60.00, auto-up, 1
monitor = desc:Ancor Communications Inc ASUS VN247 G2LMTF057181, 1920x1080@60.00, auto-up, 1
monitor = desc:Ancor Communications Inc ASUS VN247 F1LMTF033327, 1920x1080@60.00, auto-right, 1
monitor = desc:AOC 27B36X 2RRRAHA013122, 1920x1080@144.00, auto-up, 1
monitor = desc:AOC 27B36X 2RRRAHA013116, 1920x1080@144.00, auto-up, 1

# NOTE: for gaming we always enforce VRR, 8 bit depth is necessary to allow direct scanout to work
monitor = desc:ASUSTek COMPUTER INC XG27AQDMGR T9LMTF126923, 2560x1440@240.00, auto-up, 1, vrr, 1, bitdepth, 8
monitor = desc:Samsung Electric Company LC32G7xT HNATC01677, 2560x1440@240.00, auto, 1, vrr, 1, bitdepth, 8
monitor = , preferred, auto-up, 1 # Fallback

# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Laptop reserved
workspace = 6, monitor:$laptop
workspace = 7, monitor:$laptop
workspace = 8, monitor:$laptop
workspace = 9, monitor:$laptop
workspace = 10, monitor:$laptop

# External reserved 
workspace = 1, monitor:m[1]
workspace = 2, monitor:m[1]
workspace = 3, monitor:m[1]
workspace = 4, monitor:m[1]
workspace = 5, monitor:m[1]

# Of course with just one monitor these do not apply
