################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# Syntax: monitor = name, res@hz, position, scale

# Monitors
$laptop = eDP-1

# Primary Monitor
monitor = $laptop, 1920x1080@144, 0x0, 1

# Specific Profiles
monitor = desc:AOC 27B36X 2RRRAHA013122, 1920x1080@144, auto-up, 1
monitor = desc:AOC 27B36X 2RRRAHA013116, 1920x1080@144, auto-up, 1
monitor = desc:ASUSTek COMPUTER INC XG27AQDMGR T9LMTF126923, 1920x1080@50.00, auto-up, 1
monitor = desc:Ancor Communications Inc ASUS VN247 G2LMTF057181, 1920x1080@60.00, auto-up, 1
monitor = desc:Ancor Communications Inc ASUS VN247 F1LMTF033327, 1920x1080@60.00, auto-right, 1
monitor = desc:OOO YZ2748, 1920x1080@60.00, auto-up, 1

# Fallback
monitor = , preferred, auto-up, 1


##################
### WORKSPACES ###
##################

# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Laptop Reserved
workspace = 1, monitor:$laptop
workspace = 2, monitor:$laptop
workspace = 3, monitor:$laptop
workspace = 4, monitor:$laptop
workspace = 5, monitor:$laptop

# External Reserved (if no monitor is connected the primary takes them)
workspace = 6, monitor:desc:AOC 27B36X 2RRRAHA013122
workspace = 7, monitor:desc:AOC 27B36X 2RRRAHA013122
workspace = 8, monitor:desc:AOC 27B36X 2RRRAHA013122
workspace = 9, monitor:desc:AOC 27B36X 2RRRAHA013122
workspace = 10, monitor:desc:AOC 27B36X 2RRRAHA013122

workspace = 6, monitor:desc:AOC 27B36X 2RRRAHA013116
workspace = 7, monitor:desc:AOC 27B36X 2RRRAHA013116
workspace = 8, monitor:desc:AOC 27B36X 2RRRAHA013116
workspace = 9, monitor:desc:AOC 27B36X 2RRRAHA013116
workspace = 10, monitor:desc:AOC 27B36X 2RRRAHA013116

workspace = 6, monitor:desc:ASUSTek COMPUTER INC XG27AQDMGR T9LMTF126923
workspace = 7, monitor:desc:ASUSTek COMPUTER INC XG27AQDMGR T9LMTF126923
workspace = 8, monitor:desc:ASUSTek COMPUTER INC XG27AQDMGR T9LMTF126923
workspace = 9, monitor:desc:ASUSTek COMPUTER INC XG27AQDMGR T9LMTF126923
workspace = 10, monitor:desc:ASUSTek COMPUTER INC XG27AQDMGR T9LMTF126923

workspace = 6, monitor:desc:Ancor Communications Inc ASUS VN247 G2LMTF057181
workspace = 7, monitor:desc:Ancor Communications Inc ASUS VN247 G2LMTF057181
workspace = 8, monitor:desc:Ancor Communications Inc ASUS VN247 G2LMTF057181
workspace = 9, monitor:desc:Ancor Communications Inc ASUS VN247 G2LMTF057181
workspace = 10, monitor:desc:Ancor Communications Inc ASUS VN247 G2LMTF057181

workspace = 6, monitor:desc:Ancor Communications Inc ASUS VN247 F1LMTF033327
workspace = 7, monitor:desc:Ancor Communications Inc ASUS VN247 F1LMTF033327
workspace = 8, monitor:desc:Ancor Communications Inc ASUS VN247 F1LMTF033327
workspace = 9, monitor:desc:Ancor Communications Inc ASUS VN247 F1LMTF033327
workspace = 10, monitor:desc:Ancor Communications Inc ASUS VN247 F1LMTF033327

workspace = 6, monitor:desc:OOO YZ2748
workspace = 7, monitor:desc:OOO YZ2748
workspace = 8, monitor:desc:OOO YZ2748
workspace = 9, monitor:desc:OOO YZ2748
workspace = 10, monitor:desc:OOO YZ2748

