###################
### PERFORMANCE ###
###################

# TODO: should make some LUA logic that optimizes performanc on-the-fly when a game is running, 
# and reverts to normal when the game is closed. For competitive gaming on Hyprland, 
# the tweaks that actually matter fall into a few buckets: 
#  - input latency
#  - tearing/frame timing
#  - cutting rendering overhead

# NOTE: Tearing v. Adaptive Sync
#
#   Tearing: GPU goes as faster as possible, the monitor grabs the most recent frame. 
#     You should idealy set unlimited framerete in your games.
#
#   Adaptive Sync (VRR): The monitor will wait for the GPU to finish rendering a frame, 
#     and will display it when ready. This is better for a smooth experience, but can introduce 
#     input lag in games. You should idealy set a framerate limit in your games to match your monitor's
#     refresh rate, minus 3~4 FPS to always stay on sync.
#
#   We will generally set VRR for all games (contet==game), and tearing only for competitive titles (e.g. Overwatch, Deadlock etc.)
#   on other DEs like KDE tearing and VRR can be set both on, on Hyprland instead this can cause flikering and stuttering, 
#   so we will set tearing only for competitive titles, and VRR for all games.

# https://wiki.hypr.land/Configuring/Variables/#general
general {
    # Master switch to allow screen tearing.
    # This only enables the capability of tearing. Windows will NOT tear unless:
    #   - they in fullscreen 
    #   - are the only visible element on screen (no notifications, no bars, no volume control)
    #   - have an 'immediate = yes' windowrule (rules.conf) to them dedicated
    allow_tearing = true
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#cursor
cursor {
    # Force hardware cursors OFF. Hardware cursor make the GPU generate a second layer dedicated to the cursor,
    # which theoretically reduces latency, as the software do not have to artificially remove pixels where the cursor is sitting
    # however, in practice this creates issues with tearing (due to experimentality of such feature)
    # 0 - use hw cursors if possible, 1 - don’t use hw cursors, 2 - auto (disable when tearing)
    no_hardware_cursors = 2

    # Makes hardware cursors use a CPU buffer. Required on Nvidia to have HW cursors. 
    # 0 - off, 1 - on, 2 - auto (nvidia only)
    use_cpu_buffer = 2

    # Disables scheduling new frames on cursor movement for fullscreen apps with VRR enabled 
    # to avoid framerate spikes (may require no_hardware_cursors = true) 
    # 0 - off, 1 - on, 2 - auto (on with content type ‘game’)
    no_break_fs_vrr = 2
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#render
render {
    # Enables direct scanout. Direct scanout attempts to reduce lag when there is only one
    # fullscreen application on a screen (e.g. game). It is also recommended to set this to false 
    # if the fullscreen application shows graphical glitches. 
    # 0 - off, 1 - on, 2 - auto (on with content type ‘game’)
    direct_scanout = 2
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    # Controls the VRR (Adaptive Sync) of your monitors. 
    # 0 - off, 1 - on, 2 - fullscreen only, 3 - fullscreen with video or game content type
    vrr = 3
}
