###############
### WINDOWS ###
###############

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Ignore maximize requests from all apps. You'll probably like this.
windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

# System Monitor workspace
windowrule {
    name = sysmon-workspace-title
    match:title = ^(btop|nvtop|htop|top)$
    workspace = special:sysmon
}

# Communication workspace
windowrule {
    name = comms-workspace-class
    match:class = ^(discord|equibop|vesktop|org.telegram.desktop|whatsapp|Element)$
    workspace = special:communication
}

# Password managers workspace
windowrule {
  name = password-workspace-class
  match:class = ^(org.keepassxc.KeePassXC)
  workspace = special:password
}

# Audio managers workspace
windowrule {
  name = audio-workspace-class
  match:class = ^(easyeffects)
  workspace = special:audio
}

# Music workspace
windowrule {
    name = music-workspace-class
    match:class = ^([Ss]potify|feishin|Supersonic|Cider|com.github.th_ch.youtube_music|Plexamp)$
    workspace = special:music
}

# Music workspace
windowrule {
    name = music-workspace-title
    match:initial_title = ^Spotify( (Premium|Free))?$
    workspace = special:music
}

# Small utilities (only calculator for now)
windowrule {
    name = gnome-calculator
    match:class = ^(org\.gnome\.Calculator)$

    # Small, floating, and pinned regardless of the workspace
    float = yes
    size = 400 600
    center = yes
    pin = yes
}

# Game Launchers Workspace
windowrule {
    name = games-launchers-workspace-class
    # Matches Steam, Lutris, and Heroic (com.heroicgameslauncher.hgl)
    match:class = ^(steam|lutris|com.heroicgameslauncher.hgl|heroic)$
    workspace = special:games
}

# Games do not belong to any workspace (love is VRRTest)
windowrule {
    name = games-stay-on-main-workspace
    match:class = ^(steam_app_.*|.*\.exe|wine|Wine|lutris_.*|heroic_.*|love)$
    workspace = unset
    content = game
}

windowrule {
    name = "VRR Test"
    match:class = ^(love)$
    no_vrr = true
    immediate = yes
}

# Competitive games should prefer tearing over VRR + other improvmeents
# TODO: unfortunately, overwatch seems to not respond to vrr, nor tearing, nor direct_scanout
windowrule {
    name = competitive-overwatch
    tag = "competitive"
    match:title = ^(Overwatch)$

    # Tearing over VRR
    no_vrr = true
    immediate = yes

    # Disable effects
    no_anim = true
    no_blur = true
    no_shadow = true
    no_dim = true
    rounding = 0
    border_size = 0
    decorate = false
 
    # Do not sleep
    idle_inhibit = always
}

